In [20]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
%matplotlib inline 
import matplotlib.pyplot as plt
import pickle

In [21]:
df_nilai = pd.read_csv('nilai_sample.csv', sep=';')
df_nilai

mtk  bahasa_indo  pendidikan_agama  ipa  ips   pernyataan
0    75           77                92   62   93        lulus
1    84           69                63   95   87        lulus
2    66           97                92   92   70        lulus
3    75           67                97   65   82        lulus
4    58           96                98   50   77        lulus
5    98           58                92   90   63        lulus
6    76           65                82   88   84        lulus
7    56           65                99   60   77        lulus
8    58           69                87   72   81        lulus
9    64           62                52   51   56  tidak_lulus
10   82           55                83   90   69        lulus
11   71           97                66   53   95        lulus
12   52          100                64   71   54  tidak_lulus
13   95           95                99   73   65        lulus
14  100           61                67  100   70        lulus
15   67           57                98   79   81        lulus
16   60           66                62   99   54  tidak_lulus
17   97           65                88   90   69        lulus
18   53           94                93   99   69        lulus

In [22]:
df_nilai.dtypes

mtk                  int64
bahasa_indo          int64
pendidikan_agama     int64
ipa                  int64
ips                  int64
pernyataan          object
dtype: object

In [23]:
feature_df = df_nilai[['mtk', 'bahasa_indo', 'pendidikan_agama', 'ipa', 'ips']]
X = np.asarray(feature_df)
X

array([[ 75,  77,  92,  62,  93],
       [ 84,  69,  63,  95,  87],
       [ 66,  97,  92,  92,  70],
       [ 75,  67,  97,  65,  82],
       [ 58,  96,  98,  50,  77],
       [ 98,  58,  92,  90,  63],
       [ 76,  65,  82,  88,  84],
       [ 56,  65,  99,  60,  77],
       [ 58,  69,  87,  72,  81],
       [ 64,  62,  52,  51,  56],
       [ 82,  55,  83,  90,  69],
       [ 71,  97,  66,  53,  95],
       [ 52, 100,  64,  71,  54],
       [ 95,  95,  99,  73,  65],
       [100,  61,  67, 100,  70],
       [ 67,  57,  98,  79,  81],
       [ 60,  66,  62,  99,  54],
       [ 97,  65,  88,  90,  69],
       [ 53,  94,  93,  99,  69]], dtype=int64)

In [26]:
# # label_encoder object knows how to understand word labels. 
# label_encoder = preprocessing.LabelEncoder() 
  
# # Encode labels in column 'species'. 
# df_nilai['pernyataan']= label_encoder.fit_transform(df_nilai['pernyataan'])
# y = np.asanyarray(df_nilai['pernyataan'].astype(int))
# y

y = df_nilai.iloc[:,-1:]
y

pernyataan
0         lulus
1         lulus
2         lulus
3         lulus
4         lulus
5         lulus
6         lulus
7         lulus
8         lulus
9   tidak_lulus
10        lulus
11        lulus
12  tidak_lulus
13        lulus
14        lulus
15        lulus
16  tidak_lulus
17        lulus
18        lulus

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (13, 5) (13, 1)
Test set: (6, 5) (6, 1)


In [28]:
X_train

array([[ 60,  66,  62,  99,  54],
       [ 75,  77,  92,  62,  93],
       [ 82,  55,  83,  90,  69],
       [ 75,  67,  97,  65,  82],
       [ 56,  65,  99,  60,  77],
       [ 98,  58,  92,  90,  63],
       [ 95,  95,  99,  73,  65],
       [ 76,  65,  82,  88,  84],
       [ 66,  97,  92,  92,  70],
       [ 67,  57,  98,  79,  81],
       [ 97,  65,  88,  90,  69],
       [ 52, 100,  64,  71,  54],
       [ 53,  94,  93,  99,  69]], dtype=int64)

In [29]:
y_train

pernyataan
16  tidak_lulus
0         lulus
10        lulus
3         lulus
7         lulus
5         lulus
13        lulus
6         lulus
2         lulus
15        lulus
17        lulus
12  tidak_lulus
18        lulus

In [30]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

C:\Users\N. Prasetio\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='liblinear',
          tol=0.0001, verbose=0, warm_start=False)

In [31]:
yhat = LR.predict(X_test)
yhat

array(['lulus', 'lulus', 'lulus', 'lulus', 'lulus', 'lulus'], dtype=object)

In [32]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.99057828, 0.00942172],
       [0.72445862, 0.27554138],
       [0.98322326, 0.01677674],
       [0.79585291, 0.20414709],
       [0.73500285, 0.26499715],
       [0.89516134, 0.10483866]])

In [33]:
# Saving model using pickle
pickle.dump(LR, open('baru_model.pkl','wb'))

In [34]:
model = pickle.load( open('baru_model.pkl','rb'))
model.predict([[50,60,70,80,90]])

array(['lulus'], dtype=object)